### ISSUE TITLE
Implement prediction mode

### ISSUE THREAD

**Issue by TheresaSchmidt** [interactive-cookbook/alignment-models#4]
Right now, the alignment model can only be run for training. Prediction mode should take a pair of recipes and predict alignments (output in human-readable format). 
Prediction output could also be the k best alignments for a source action (we were thinking about displaying the k best option during crowdsourcing round 2).

**Comment by irisferrazzo** [comment]
Top k alignments implemented. The predictions made by the alignment, independently from their amount, can be now extracted.
